### ISSUE TITLE
config-overrides.js 中直接配置darkTheme无法生效

### ISSUE THREAD

**Issue by Altamill** [ant-design/ant-design-dark-theme#19]
`const {
  override,
  fixBabelImports,
  addLessLoader,
} = require("customize-cra");

const darkTheme = require("@ant-design/dark-theme");

process.env.GENERATE_SOURCEMAP = "false";   //打包时去除map文件
module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd",
    libraryDirectory: "es",
    style: true // change importing css to less
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: darkTheme
  })
);`

**Comment by chenshuai2144** [comment]
config-overrides 是什么东西？

**Comment by Altamill** [comment]
https://ant.design/docs/react/use-with-create-react-app-cn
此链接中的高级配置项下有详细说明这个文件的用处，个人理解应该是用来按需加载样式用的。

**Comment by Altamill** [comment]
https://ant.design/docs/react/use-with-create-react-app-cn
此链接中的高级配置项下有详细说明这个文件的用处，个人理解应该是用来按需加载样式用的。

**Comment by afc163** [comment]
```diff
- const darkTheme = require("@ant-design/dark-theme");
+ const darkTheme = require("@ant-design/dark-theme").default;
```

Try it.

**Comment by afc163** [comment]
或者 console.log(darkTheme) 看看是啥。

**Comment by Altamill** [comment]
console.log(darkTheme)是@ant-design  dark-theme 目录下 inde.js 文件中的样式

**Comment by Altamill** [comment]
const darkTheme = require("@ant-design/dark-theme").default;
更改之后只有部分样式被覆盖，字体以及按钮等其他样式还是原来的
![image](https://user-images.githubusercontent.com/22368026/70874894-177e0100-1fef-11ea-888f-63d551737be7.png)

**Comment by afc163** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/507615/70876429-8a3dab00-1ff4-11ea-9d27-4edc01cd472b.png">

`@ant-design/dark-theme` 还不完善，欢迎给我们 PR。
